### ISSUE TITLE
Firmware misspelled in StatusFrame.h

### ISSUE THREAD

**Issue by kjaget** [CrossTheRoadElec/Phoenix-Releases#14]
Sorry for being horribly nit-picky, close if it doesn't matter.

Not sure if intentional but `Status_15_FirmareApiStatus` in StatusFrame.h is missing a w in both cases.

**Comment by CoryNessCTR** [comment]
Release https://github.com/CrossTheRoadElec/Phoenix-Releases/releases/tag/v5.21.1.0 has this fixed
