### ISSUE TITLE
Weird behavior with open loop ramp in simulation

### ISSUE THREAD

**Issue by prateekma** [CrossTheRoadElec/Phoenix-Releases#16]
The robot does not drive straight when an open-loop ramp rate is configured.

**Steps to Reproduce:**
 - Clone the [DifferentialDrive_Simulation example](https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/tree/master/Java%20General/DifferentialDrive_Simulation).
 - Add the following code to the end of `robotInit()` in `Robot.java`:

```
m_leftDrive.configOpenloopRamp(0.2);
m_rightDrive.configOpenloopRamp(0.2);
```

 - Launch simulation and drive forward (to ensure that no sideways inputs are being provided, drag Keyboard 0 to Joystick 0 and hold W).

**Expected Behavior:**

Remove the two lines of code above, run simulation, and drive forward. The robot's heading does not change.

**Comment by CoryNessCTR** [comment]
This is fixed in 5.20.2.2
