### ISSUE TITLE
Additional Plots for Motion Magic Tuning

### ISSUE THREAD

**Issue by Kython89** [CrossTheRoadElec/Phoenix-Releases#2]
![image](https://user-images.githubusercontent.com/13496307/52530101-8a2e9980-2cc5-11e9-949d-3907bdf494cf.png)

Any chance of getting plots so that MotionMagic can be fully tuned from Tuner?  Specifically the following two plots are missing.
1. ActTraj_Position
2. ActTraj_Velocity

**Comment by ozrien** [comment]
Fixed in v5.14
Also just posted...
https://phoenix-documentation.readthedocs.io/en/latest/blog/blog-week6.html
