### ISSUE TITLE
Feture Request: Plot CANCoder Values

### ISSUE THREAD

**Issue by jonathandao0** [CrossTheRoadElec/Phoenix-Releases#26]
Add the ability to plot a CANCoder's value over time using the plot feature. Currently the only way to plot these values is if you assign the CANCoder to a CTRE motor controller.

**Comment by JCaporuscio** [comment]
This feature is available in Phoenix Tuner X, so closing the issue

https://apps.microsoft.com/store/detail/phoenix-tuner-x/9NVV4PWDW27Z
