### ISSUE TITLE
Feature Request: TalonFX {Get/Set}SlotConfiguration(int slotid)

### ISSUE THREAD

**Issue by dawonn** [CrossTheRoadElec/Phoenix-Releases#27]
Would be handy to be able to Get/Set a SlotConfiguration for a a motor with one command without resorting to the 'allconfigs' version that pulls in much more data. 

`struct ctre::phoenix::motorcontrol::can::SlotConfiguration` to be precise.

**Comment by JCaporuscio** [comment]
This has been implemented in the latest release:
https://github.com/CrossTheRoadElec/Phoenix-Releases/releases/tag/v5.21.2.0
