### ISSUE TITLE
Combine Axes of like measurements.

### ISSUE THREAD

**Issue by Kython89** [CrossTheRoadElec/Phoenix-Releases#3]
First of all.  We love Tuner.  It is a valuable tool that allows us to tune mechanisms very quickly.  One thing that students and mentors both have struggled with is the overwhelming number of axes.  In our minds it would make more sense if some of the parameters being plotted shared axes.

1. Target Pos and Pos
2. Target Velocity and Velocity

Currently a quick glance might have you think the mechanism is or isn't tracking as expected when the opposite is happening because of the independent auto scaling that occurs on each axes.

ex.  The plots lead one to believe that the mechanism is tracking decently.  Upon closer inspection the Position is thousands less than the Target Velocity.

If there is a use case we are missing where this doesn't make sense then could this functionality be added as an option?

**Comment by daltzctr** [comment]
This has been resolved.

Phoenix Tuner X Preview 2025.1.0.0 has the ability to group axis's together so all changes are duplicated across them.
