### ISSUE TITLE
Native (firmware) support for `setVoltage`

### ISSUE THREAD

**Issue by Oblarg** [CrossTheRoadElec/Phoenix-Releases#31]
The WPILib `setVoltage` method has a functional default behavior, but the Talon's internal voltage compensation is almost certainly better.  It'd be nice if the WPILib method would delegate to the internal motor controller firmware for the voltage compensation - this would also eliminate the need to warn users of `setVoltage` when voltage compensation is enabled.

This doesn't necessarily fit cleanly into the current user-side API architecture, but I think the increase in user experience would probably be worth the engineering cost.  As it stands, a lot of effort is spent explaining to users how to delegate to Talon voltage control when using on-RIO control loops - if the function delegated, this would work "automatically."

**Comment by JCaporuscio** [comment]
This is now available to all users with Phoenix v6, so closing the issue
