### ISSUE TITLE
Build Failing Due to Reference to a Nonexistent File

### ISSUE THREAD

**Issue by ankithm28** [CrossTheRoadElec/Phoenix-Releases#37]
We're referencing the `Talon FX` motor controller. This raises an error on compilation that there is a reference to `Platform.hpp`. 

`#include "ctre/phoenix/platform/Platform.hpp"`
<img width="935" alt="Screen Shot 2023-01-14 at 5 39 35 PM" src="https://user-images.githubusercontent.com/40261054/212506547-a21c4e3c-fc90-49b9-9c71-e6581dd309bc.png">
<img width="1065" alt="Screen Shot 2023-01-14 at 5 39 54 PM" src="https://user-images.githubusercontent.com/40261054/212506664-6c1f0720-dc45-4487-a2a1-41db0123c463.png">

The documentation at `https://api.ctr-electronics.com/phoenix/release/cpp/_platform___c_c_i_8h_source.html` also references this file but doesn't exist.

Thanks for the help!

**Comment by ozrien** [comment]
Header file appears to be there on my side.  I pulled [Motion Magic Example](https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/tree/master/C%2B%2B%20General/MotionMagic) to quick test and it builds (sim and rio).

My guess is the [Phoenix.json](https://github.com/CrossTheRoadElec/Phoenix-Examples-Languages/blob/master/C%2B%2B%20General/MotionMagic/vendordeps/Phoenix.json) is wrong in your project.

**Comment by ozrien** [comment]
If its easy you can send us your project and we can take a quick look.
