### ISSUE TITLE
Phoenix pro motion magic not handling inversion properly

### ISSUE THREAD

**Issue by mjansen4857** [CrossTheRoadElec/Phoenix-Releases#40]
In simulation at least, I can't speak for a real robot yet. When using motion magic (possibly other position/velocity control modes as well), inversion is not being handled properly. 

When inverted (clockwise positive), if I set a positive target position, the motor will be driven in the correct direction (clockwise), but it will target a position in the opposite direction (negative/counter clockwise). Because the motor output and sensor value is being inverted, motion magic will be targeting a negative position while driving in the positive direction, so the target is never reached.

**Comment by ozrien** [comment]
Phoenix 5 or Phoenix Pro?
Note there was  Phoenix Pro fix last week ([Change log](https://api.ctr-electronics.com/changelog) 2023/01/30) that addresses an issue with invert.

**Comment by mjansen4857** [comment]
Phoenix pro. We are using the latest update. It seems to work fine on a real robot.

**Comment by JCaporuscio** [comment]
Closing as complete - this was fixed in 23.0.7
https://api.ctr-electronics.com/changelog#20230210
