### ISSUE TITLE
Add Python Simulation Support to Phoenix 6

### ISSUE THREAD

**Issue by lospugs** [CrossTheRoadElec/Phoenix-Releases#52]
I was attempting to test out the Phoenix 6 Python API by porting the java CommandBasedDrive example to Python to try out the beta. 
Missing method: set_position from TalonFXConfigurator
Missing Classes: TalonFXSimState

I then ported some older code that simulates well (in that the robot moves on the screen, etc) with the robotpy Phoenix5 just to try out the beta. 

Working and not working code is here for reference:
https://github.com/Lambda-Corps/2024_Python_beta

**Comment by JCaporuscio** [comment]
Yep - the simulation functions in Python are on our near-term roadmap.
No exact ETA I can provide yet but it should be coming soon.

**Comment by bhall-ctre** [comment]
This has been added with the release of Phoenix 6 2024 beta 3: https://api.ctr-electronics.com/changelog#20231122
