### ISSUE TITLE
Typo in `WPI_TalonFX.class`

### ISSUE THREAD

**Issue by Daniel-E-B** [CrossTheRoadElec/Phoenix-Releases#6]
In the package `com.ctre.phoenix.motorcontrol.can` file `WPI_TalonFX.class`, there is a typo on line 56 which registers the Talon FX in the `SendableRegistry` as a `Talon SRX `, which makes it appear incorrectly on OutlineViewer and dashboard software.

Line 56:
`SendableRegistry.addLW(this, "Talon SRX ", deviceNumber);`

**Comment by JCaporuscio** [comment]
This was fixed in the 5.17.6 release of Phoenix.
