### ISSUE TITLE
Python phoenix6 package is unusable for type checking

### ISSUE THREAD

**Issue by auscompgeek** [CrossTheRoadElec/Phoenix-Releases#61]
We're unable to run the mypy type checker on our robot code after migrating to `phoenix6`. Example output:

```
Error: components/chassis.py:3:1: error: Skipping analyzing "phoenix6": module is installed, but missing library stubs or py.typed marker  [import-untyped]
components/chassis.py:3:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

Could we please get a `py.typed` marker file in the package, per [PEP 561](https://peps.python.org/pep-0561/)?

**Comment by CoryNessCTR** [comment]
This is fixed in the 24.1.0 release

**Comment by auscompgeek** [comment]
I'm not seeing a `py.typed` in the `phoenix6` package in 24.1.0.

**Comment by auscompgeek** [comment]
I can confirm phoenix6 24.2.0 has a `py.typed`; thanks!
