### ISSUE TITLE
Some python static methods aren't marked as static

### ISSUE THREAD

**Issue by TheTripleV** [CrossTheRoadElec/Phoenix-Releases#66]
For example (there's a couple), wait_for_all is a static function in BaseStatusSignal but appears as a valid function to use on a StatusSignal even though it isn't.
Either
1. If these are meant to be static, these should be marked as static with the `@staticmethod` decorator
2. If these are meant to be not static, these should have a self parameter added to have them work properly as instance methods.
<img width="814" alt="Screenshot 2024-01-22 at 11 53 30 PM" src="https://github.com/CrossTheRoadElec/Phoenix-Releases/assets/11065157/4992d817-2907-46eb-8fde-2b022d084cb3">

**Comment by bhall-ctre** [comment]
This should be fixed in 24.3.0.
