### ISSUE TITLE
Device Firmware Update Improvements

### ISSUE THREAD

**Issue by modelmat** [CrossTheRoadElec/Phoenix-Releases#7]
Currently, the Update Firmware area looks a bit like:
![image](https://user-images.githubusercontent.com/25718989/75101212-f4924d80-562c-11ea-8e3d-23c2b7cd205b.png)
I only recently noticed that the Phoenix Tuner came with a few firmware files located in `C:\Users\Public\Documents\FRC`, and that you didn't have to manually download the various firmware versions from the website by yourself.

I have seen no indication anywhere that this exists, and other members of my team also didn't know about these files.

I believe something similar to the below dialogue could vastly improve our experience with firmware updates:
![image](https://user-images.githubusercontent.com/25718989/75101297-99615a80-562e-11ea-923f-468312eb5112.png)

Some other (related) bits I would like to see:
- automatic detection of when devices are out of date and showing a notification alongside the device in the device list
- Filtering firmware update list based on the type of the currently selected device 
- ability to update downloaded firmware through the GUI (see the mockup)

**Comment by CoryNessCTR** [comment]
I believe most of these concerns are solved with Phoenix Tuner X.

> I believe something similar to the below dialogue could vastly improve our experience with firmware updates:

In Phoenix Tuner X, the interface looks like the following, with automatic version checking:
![image](https://user-images.githubusercontent.com/28712271/204889972-e65b0b49-5191-403b-be03-45e370ee449a.png)

> automatic detection of when devices are out of date and showing a notification alongside the device in the device list

This is managed by the green/red borders in the device view, indicating whether a device is up to date or not.
![image](https://user-images.githubusercontent.com/28712271/204890357-548e2900-dbd5-4e19-b595-d172dd8fcc3f.png)

> Filtering firmware update list

Automatically filtered in the firmware selection

> ability to update downloaded firmware through the GUI (see the mockup)

This updating mechanism uses the internet to automatically pull the latest available and flash it to the device.


That said, we likely will not be updating Phoenix Tuner v1 with these features, as Phoenix Tuner X is available for both Phoenix v5 and Phoenix Pro.

Let us know if there's anything else we may be missing, in the meantime I'm going to close this issue.
