### ISSUE TITLE
Swerve: ChassisSpeeds are not desaturated

### ISSUE THREAD

**Issue by TheTripleV** [CrossTheRoadElec/Phoenix-Releases#72]
forward from: https://discord.com/channels/176186766946992128/368993897495527424/1199545720399740928

Within the SwerveRequest interface, in 4 of the Swerve Requests, `toSwerveModuleStates` is called but `desaturateWheelSpeeds` is not called afterwards. `toSwerveModuleStates` does not automatically call `desaturateWheelSpeeds` according to the docs.

Should these SwerveRequests be calling `desaturateWheelSpeeds`?

**Comment by daltzctr** [comment]
Chassis speeds are now desaturated by default but the behavior can be disabled. See the `DesaturateWheelSpeeds` property on any of the `SwerveRequests`
