### ISSUE TITLE
Java: Return Swerve Modules as List

### ISSUE THREAD

**Issue by hamster1147** [CrossTheRoadElec/Phoenix-Releases#73]
Currently the only convenient way to get swerve modules out of `SwerveDrivetrain` is by calling `getModule(int)` with an index. With no way to access module count internal to `SwerveDrivetrain`, there isn't a convenient way to iterate over the modules without null checking. A convenient solution is to have a getter function that returns the modules as a `List<SwerveModule>`.

**Comment by daltzctr** [comment]
You can use `getModules()` ([Java](https://api.ctr-electronics.com/phoenix6/latest/java/com/ctre/phoenix6/swerve/SwerveDrivetrain.html#getModules()), [C++](https://api.ctr-electronics.com/phoenix6/latest/cpp/classctre_1_1phoenix6_1_1swerve_1_1_swerve_drivetrain.html#a37605259db2514676df4253a9e5f7a87)) to get an enumerable list
