### ISSUE TITLE
SwerveModule: open loop mode with FOC

### ISSUE THREAD

**Issue by jonahsnider** [CrossTheRoadElec/Phoenix-Releases#74]
The SwerveModule class has no way to use FOC in an open loop control mode. There is FOC and non-FOC for closed loop, but the only option for open loop is non-FOC.

`DriveRequestType` should have a `OpenLoopVoltageFOC` option added

**Comment by bhall-ctre** [comment]
Since OpenLoopVoltage uses a VoltageOut request with the default EnableFOC value of true, FOC is already enabled. The firmware just ignores it if the device is unlicensed.

**Comment by jonahsnider** [comment]
Ah, my mistake, I didn't realize the specific `VoltageOut` constructor the `SwerveModule` uses sets FOC to enabled. Sorry for missing that!
