### ISSUE TITLE
Swerve Gen Steer Motor PID configs

### ISSUE THREAD

**Issue by alexanderszura** [CrossTheRoadElec/Phoenix-Releases#83]
We are currently updating a robot to the new 2025 beta. When we created a new project for the new tuner preview for swerve gen we noticed that the steering motor would have oscillation and a lot of jitter. After some (quick) manual tuning/debugging we ended up removing all of the Feed-Forward constants which fixed the issue. We are using SDS-mk4i L2 with dual kraken, here are the steer configs of the updated PID constants.

```
private static final Slot0Configs steerGains = new Slot0Configs()
        .withKP(100).withKI(0).withKD(0.5)
        .withKS(0.0).withKV(0.0).withKA(0)
        .withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
```

Here are the old configs

```
private static final Slot0Configs steerGains = new Slot0Configs()
        .withKP(100).withKI(0).withKD(0.5)
        .withKS(0.2).withKV(2.66).withKA(0)
.withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
```

Not the biggest issue just thought I would let y'all know!

**Comment by daltzctr** [comment]
Hey Alex

Thanks for letting us know. We are actively tweaking and tuning our OOTB gains to ensure the greatest compatibility for teams through a wide range of swerve modules. Looking at your new modules, I would expect a kV of 1.5 and to try decreasing kS to 0.1. With just that, I suspect you'll have a lot better of a experience. With 100 kP and that 0.5 of a kD, I would expect drift if you drive your robot in a straight line.

**Comment by alexanderszura** [comment]
Awesome! Thanks for letting me know, I'll try that later tomorrow. Thanks for the help!
