### ISSUE TITLE
Add ability to access swerve pose buffer

### ISSUE THREAD

**Issue by gijsland** [CrossTheRoadElec/Phoenix-Releases#84]
Could you please add a method to SwerveDrivetrain to access sampleAt from PoseEstimator? Getting the pose at a previous timestamp can be helpful when dealing with camera latency.

https://github.com/wpilibsuite/allwpilib/blob/main/wpimath/src/main/native/include/frc/estimator/PoseEstimator.h#L172
https://github.com/wpilibsuite/allwpilib/blob/main/wpimath/src/main/java/edu/wpi/first/math/estimator/PoseEstimator.java#L180

**Comment by bhall-ctre** [comment]
This has been added in beta-4 ([changelog](https://api.ctr-electronics.com/changelog#20241212)).
