### ISSUE TITLE
Use https in vendordep json

### ISSUE THREAD

**Issue by sciencewhiz** [CrossTheRoadElec/Phoenix-Releases#9]
Gradle warns about using non-secure links.

**Comment by JCaporuscio** [comment]
I've fixed this for our upcoming kickoff release, so once that's published it will be fixed.

**Comment by JCaporuscio** [comment]
Fixed in our [latest release](https://github.com/CrossTheRoadElec/Phoenix-Releases/releases/tag/v5.19.4.1) and in Phoenix-latest.json on our maven repository.
